FROM node:alpine
WORKDIR /opt/app
ENV PATH /opt/app/node_modules/.bin:$PATH
#COPY ./app/package.json ./
#COPY ./app/package-lock.json ./
#RUN npm i -g npm
#USER node
RUN apk add -U --no-cache git
RUN git clone https://github.com/xoneUpx/cedit.git .
#UN npm i --prefix ./app
#WORKDIR ./app
#npm build and run on server
#RUN chmod -R 0777 /opt/app/node_modules
#for development on k8s
#RUN ["npm", "start"]
#RUN npm i -D
