FROM node:alpine
WORKDIR /opt/app
ENV PATH /opt/app/node_modules/.bin:$PATH
#COPY ./app/package.json ./
#COPY ./app/package-lock.json ./
#RUN npm i -g npm
#USER node
RUN apk -U --no-cache add git
RUN git clone https://github.com/xoneUpx/cedit.git .
RUN npm i
#npm build and run on server
RUN chmod -R 0777 /opt/app/node_modules
#for development on k8s
RUN ["npm", "start"]
#RUN npm i -D
